runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  PROJECT_ID: "1045313635820"
  LOCATION: "us-central1"
  MODEL_ENDPOINT: "projects/1045313635820/locations/us-central1/endpoints/4604224732521299968"

handlers:
- url: /static
  static_dir: static
- url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg))$
  static_files: static/\1
  upload: static/.*\.(js|css|png|jpg|jpeg|gif|ico|svg)$
- url: /.*
  script: auto